package org.opennms.netmgt.correlation.drools;

import java.util.Date;

import org.opennms.core.utils.InetAddressUtils;
import org.opennms.netmgt.correlation.drools.DroolsCorrelationEngine;
import org.opennms.netmgt.xml.event.Event;
import org.opennms.netmgt.model.events.EventBuilder;
import org.opennms.netmgt.events.api.EventConstants;
import org.opennms.netmgt.model.events.EventUtils;

global org.opennms.netmgt.correlation.drools.DroolsCorrelationEngine engine;
global org.opennms.netmgt.correlation.drools.NodeService nodeService;
global java.lang.Integer CONN_RATE_HIGH_TRIGGER_COUNT;
global java.lang.Integer CONN_RATE_HIGH_TIME_WINDOW;


/*
 * 3) (Aggregation) If you receive > CONN_RATE_HIGH_TRIGGER_COUNT times connectionRateHigh
 * Inside a period of CONN_RATE_HIGH_TIME_WINDOW milliseconds
 * Then generate one single critical alarm to be forwarded via SNMP to VizGems
 * and email to nmsadmin@att.com.
 */

declare HighConnectionRateSituation
	node : Long
	timerId : Integer
	occurrences : Integer
end

rule "initial connectionRateHigh event received for node"
	salience 100
	when
		$e : Event( $uei : uei == "uei.opennms.org/vendor/Juniper/MFC/traps/connectionRateHigh", $nodeid : nodeid, $ipaddr : interface )
		not( HighConnectionRateSituation( node == $nodeid ) )
	then
		retract( $e );
		HighConnectionRateSituation situation = new HighConnectionRateSituation();
		situation.setNode( $nodeid );
		situation.setTimerId( engine.setTimer( CONN_RATE_HIGH_TIME_WINDOW ) );
		situation.setOccurrences( 1 );
		insert( situation );
		println( "Found connectionRateHigh event for node " + $nodeid +". Inserted new situation " + situation + " and retracted event." );
		println( "Note: CONN_RATE_HIGH_TRIGGER_COUNT is set to " + CONN_RATE_HIGH_TRIGGER_COUNT );
end

rule "subsequent but NON-triggering connectionRateHigh event received for node"
	salience 100
	when
		$e : Event( $uei : uei == "uei.opennms.org/vendor/Juniper/MFC/traps/connectionRateHigh", $nodeid : nodeid, $ipaddr : interface )
		$situation : HighConnectionRateSituation( occurrences < ( CONN_RATE_HIGH_TRIGGER_COUNT ), node == $nodeid )
	then
		println( "Found connectionRateHigh event for active situation " + $situation + ". Retracting event. Incrementing occurrences on situation." );
		retract( $e );
		incrementOccurrences( $situation );
		update( $situation );
end

rule "subsequent TRIGGERING connectionRateHigh event received for node"
	salience 1000
	when
		$e : Event( $uei : uei == "uei.opennms.org/vendor/Juniper/MFC/traps/connectionRateHigh", $nodeid : nodeid, $ipaddr : interface )
		$situation : HighConnectionRateSituation( $occ : occurrences >= ( CONN_RATE_HIGH_TRIGGER_COUNT ), node == $nodeid )
	then
		println( "Final connectionRateHigh event on situation " + $situation + " triggered critical event, retracting event and situation; sending escalation event" );
		retract( $e );
		retract( $situation );
		sendCriticalConnRateHighEvent( engine, $nodeid, $ipaddr, CONN_RATE_HIGH_TRIGGER_COUNT, CONN_RATE_HIGH_TIME_WINDOW );
end

rule "retract expired connectionRateHigh situations"
	when
		$situation : HighConnectionRateSituation( $nodeid : node, $timerId : timerId, $occ : occurrences < ( CONN_RATE_HIGH_TRIGGER_COUNT ) )
		$expiration : TimerExpired( id == $timerId )
	then
		println( "Found expired connectionRateHigh situation " + $situation + "; retracting situation and expiration." );
		retract( $situation );
		retract( $expiration );
end


function void incrementOccurrences( HighConnectionRateSituation situation ) {
	Integer occ = situation.getOccurrences();
	occ++;
	situation.setOccurrences( occ );
}

function void sendCriticalConnRateHighEvent( DroolsCorrelationEngine engine, Long nodeId, String ipAddr, Integer count, Integer timeWindow ) {
		Integer timeWindowMinutes = timeWindow / 60000;
        EventBuilder bldr = new EventBuilder("uei.opennms.org/vendor/Juniper/MFC/correlation/aggregateConnectionRateHigh", "Drools")
                .setNodeid(nodeId.intValue())
                .setInterface(InetAddressUtils.addr(ipAddr))
		.addParam("correlationEngineName", "Drools")
		.addParam("correlationRuleSetName", engine.getName())
		.addParam("correlationComments", "Observed at least " + count + " occurrences within " + timeWindowMinutes + " minutes")
		.addParam("occurrences", count.toString())
		.addParam("timeWindow", timeWindowMinutes.toString());
        engine.sendEvent(bldr.getEvent());
}

function void println(Object msg) {
	System.out.println(new Date() + " : " + msg);
}