package org.opennms.netmgt.correlation.drools;

import java.util.Date;

import org.opennms.core.utils.InetAddressUtils;
import org.opennms.netmgt.correlation.drools.DroolsCorrelationEngine;
import org.opennms.netmgt.xml.event.Event;
import org.opennms.netmgt.model.events.EventBuilder;
import org.opennms.netmgt.EventConstants;
import org.opennms.netmgt.capsd.EventUtils;

global org.opennms.netmgt.correlation.drools.DroolsCorrelationEngine engine;
global org.opennms.netmgt.correlation.drools.NodeService nodeService;
global java.lang.Integer NODE_DOWN_HOLDDOWN_TIME;


/*
 * 11)  (Action triggering) If Node down (any MFC) 
 * Then wait 30 seconds,
 * If Trap is cancelled then Disregard
 * Else  generate 1 single critical alarm to be forwarded via SNMP to VizGems (IP addess) and email to  nmsadmin@att.com 
 */

declare NodeDownSituation
	node : Long
	timerId : Integer
end

rule "nodeDown event received for node"
	salience 100
	when
		$e : Event( $uei : uei == "uei.opennms.org/nodes/nodeDown", $nodeid : nodeid )
		not( NodeDownSituation( node == $nodeid ) )
	then
		retract( $e );
		NodeDownSituation situation = new NodeDownSituation();
		situation.setNode( $nodeid );
		situation.setTimerId( engine.setTimer( NODE_DOWN_HOLDDOWN_TIME ) );
		insert( situation );
		println( "Found nodeDown event for node " + $nodeid +". Inserted new situation " + situation + " and retracted event." );
end

rule "nodeUp event received for node with existing nodeDown situation"
	salience 100
	when
		$e : Event( $uei : uei == "uei.opennms.org/nodes/nodeUp", $nodeid : nodeid )
		$situation : NodeDownSituation( node == $nodeid )
	then
		retract( $e );
		retract( $situation );
		println( "Found nodeUp event for node with NodeDownSituation " + $situation + ". Retracted nodeUp and situation. End of line." );
end

rule "timer expired on a NodeDownSituation"
	salience 1000
	when
		$expiration : TimerExpired( $timerId : id )
		$situation : NodeDownSituation( timerId == $timerId, $nodeid : node )
	then
		println( "Hold-down timer expired for NodeDownSituation " + $situation + ".  Retracting expiration and situation; sending escalation event" );
		retract( $expiration );
		retract( $situation );
		sendVerifiedNodeDownEvent( engine, $nodeid, NODE_DOWN_HOLDDOWN_TIME );
end


function void sendVerifiedNodeDownEvent( DroolsCorrelationEngine engine, Long nodeId, Integer holdDownTime ) {
		Integer holdDownTimeSec = holdDownTime / 1000;
        EventBuilder bldr = new EventBuilder("uei.opennms.org/nodes/correlation/nodeDownPastHoldDownTime", "Drools")
                .setNodeid(nodeId.intValue())
		.addParam("correlationEngineName", "Drools").
		.addParam("correlationRuleSetName", engine.getName()).
		.addParam("correlationComments", "Observed an interface-down situation enduring at least " + holdDownTimeSec + " seconds")
		.addParam("holdDownTime", holdDownTimeSec.toString());
        engine.sendEvent(bldr.getEvent());
}

function void println(Object msg) {
	System.out.println(new Date() + " : " + msg);
}
