# Cookbook Name:: onguard_opennms_wrapper
# Recipe:: Cisco node_lost_event hold timer down
# Copyright (c) 2017 ConvergeOne, All Rights Reserved.

cookbook_file "#{node['opennms']['conf']['home']}/etc/drools-engine.d/CiscoServiceDownTimerRules.drl" do
  source 'CiscoServiceDownTimerRules.drl'
  owner 'root'
  group 'root'
  mode 00644
  notifies :restart, 'service[opennms]'
end

cookbook_file "#{node['opennms']['conf']['home']}/etc/drools-engine.d/cisco-lost-node-service-drools-engine.xml" do
  source 'drools-engine.xml'
  owner 'root'
  group 'root'
  mode 00644
  notifies :restart, 'service[opennms]'
end

cisco_actual_service_event = 'uei.opennms.org/nodes/nodeLostService'
cisco_correlation_event = 'uei.opennms.org/nodes/correlation/DownTimeHoldDownTime'
file_name = 'events/opennms.events.xml'

opennms_event cisco_actual_service_event do
  file file_name
  position 'top'
  mask [{'mename' => 'uei', 'mevalue' => [cisco_actual_service_event]},
        {'mename' => 'service',
         'mevalue' => ['Cisco RTMT Reporter Servlet',
                       'A Cisco DB',
                       'A Cisco DB Replicator',
                       'Host Resources Agent',
                       'System Application Agent',
                       'Cisco Database Layer Monitor',
                       'Cisco CallManager Serviceability',
                       'Cisco CDP Agent',
                       'Cisco RIS Data Collector',
                       'Cisco CDP',
                       'MIB2 Agent',
                       'Cisco Tomcat',
                       'Cisco CallManager Serviceability RTMT',
                       'SSH',
                       'SNMP']}]
  event_label 'Cisco Actuall Service Down';
  descr 'outage identified on interface %interface% on node %nodelabel% A new Outage record has been created and service level availability calculations will be impacted until this outage is resolved.'
  logmsg ' outage identified on interface %interface% on node %nodelabel%'
  severity 'Warning'
  alarm_data false
  notifies :run, 'opennms_send_event[restart_Eventd]'
end

opennms_event cisco_correlation_event do
  file 'events/cisco-service-correlations.events.xml'
  position 'top'
  event_label 'Service occurred past hold down timer minutes'
  descr ' <p> This notification is generated by backup scripts for service </p> '
  logmsg ' This notification is generated by backup scripts for service, service name: '
  logmsg_dest 'logndisplay'
  severity 'Warning'
  alarm_data(
      'alarm_type' => 1,
      'reduction_key' => 'uei.opennms.org/nodes/nodeLostService:%dpname%:%nodeid%:%interface%:%service%',
      'auto_clean' => true
  )
  notifies :run, 'opennms_send_event[restart_Eventd]'
end


